### ISSUE TITLE
Alpine/Musl segfault when building BOLT in stage 3

### ISSUE THREAD

**Issue by Gelbpunkt** [ClangBuiltLinux/tc-build#227] opened 2023-02-01 15:00 UTC
**Describe the bug**
There are some issues with building LLVM on Alpine Linux with these scripts, I thought I'd ask here instead of opening LLVM issues.

1. llvm/include/llvm/Support/VCSRevision.h just doesn't get created for me, I have to manually add `subprocess.run(["python3", "llvm/utils/gn/build/write_vcsrevision.py", "--write-git-rev", "--name", "LLVM", "llvm/include/llvm/Support/VCSRevision.h"], check=True, cwd=llvm_folder)` after the git checkout in build-llvm.py to get it building
2. Enabling BOLT via --projects causes segmentation faults in stage 3: 
```c
[4842/4898] Linking CXX executable bin/opt
ninja: job failed: : && /build/build/llvm/stage1/bin/clang++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin -O3 -DNDEBUG -Wl,--emit-relocs -fuse-ld=/build/build/llvm/stage1/bin/ld.lld -Wl,--color-diagnostics -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin    -Wl,--gc-sections tools/bolt/tools/heatmap/CMakeFiles/llvm-bolt-heatmap.dir/heatmap.cpp.o -o bin/llvm-bolt-heatmap  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMARMCodeGen.a  lib/libLLVMARMAsmParser.a  lib/libLLVMARMDesc.a  lib/libLLVMARMDisassembler.a  lib/libLLVMARMInfo.a  lib/libLLVMARMUtils.a  lib/libLLVMAArch64CodeGen.a  lib/libLLVMAArch64AsmParser.a  lib/libLLVMAArch64Desc.a  lib/libLLVMAArch64Disassembler.a  lib/libLLVMAArch64Info.a  lib/libLLVMAArch64Utils.a  lib/libLLVMX86CodeGen.a  lib/libLLVMX86AsmParser.a  lib/libLLVMX86Desc.a  lib/libLLVMX86Disassembler.a  lib/libLLVMX86Info.a  lib/libLLVMMC.a  lib/libLLVMObject.a  lib/libLLVMSupport.a  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRewrite.a  lib/libLLVMBOLTUtils.a  lib/libLLVMipo.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMLinker.a  lib/libLLVMVectorize.a  lib/libLLVMARMDesc.a  lib/libLLVMARMInfo.a  lib/libLLVMARMUtils.a  lib/libLLVMGlobalISel.a  lib/libLLVMSelectionDAG.a  lib/libLLVMCFGuard.a  lib/libLLVMInstrumentation.a  lib/libLLVMBOLTProfile.a  lib/libLLVMDWP.a  lib/libLLVMExecutionEngine.a  lib/libLLVMOrcTargetProcess.a  lib/libLLVMOrcShared.a  lib/libLLVMBOLTRuntimeLibs.a  lib/libLLVMBOLTPasses.a  lib/libLLVMAsmPrinter.a  lib/libLLVMCodeGen.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMBitWriter.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMTarget.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMRuntimeDyld.a  lib/libLLVMBOLTTargetAArch64.a  lib/libLLVMAArch64Desc.a  lib/libLLVMAArch64Info.a  lib/libLLVMAArch64Utils.a  lib/libLLVMBOLTTargetX86.a  lib/libLLVMX86Desc.a  lib/libLLVMX86Info.a  lib/libLLVMBOLTCore.a  lib/libLLVMBOLTUtils.a  lib/libLLVMMCDisassembler.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  -lrt  -ldl  -lm  /lib/libz.so  lib/libLLVMDemangle.a && :
clang-17: error: unable to execute command: Segmentation fault (core dumped)
clang-17: error: linker command failed due to signal (use -v to see invocation)
```

**To Reproduce**
I have forked this repository and added a Dockerfile based on Alpine and a podman script that reproduce this issue.
1. Clone https://github.com/Kenvyra/tc-build
2. Install podman
3. I use a 200GB tmpfs mainly for the BOLT instrumentation data, you might want to change that in buildme.sh
6. Run `./buildme.sh`

**Expected behavior**
I expect the build to pass. It will build fine if [this line is removed](https://github.com/Kenvyra/tc-build/blob/main/build-toolchain.sh#L21), but BOLT won't be built in stage 3 if it does.

Also, I would expect VCSRevision.h to be generated.

**Screenshots**

**Environment (please complete the following information):**
  - Command you ran:
```
./build-llvm.py \
	--clang-vendor "Adrian" \
	--incremental \
	--targets "ARM;AArch64;X86" \
	--bolt \
	--pgo kernel-defconfig \
	--lto thin \
	--shallow-clone \
	--projects "clang;compiler-rt;lld;polly;bolt"
```
  - Distribution: Alpine Linux Edge
  - Python version: 3.11.1
  - Shell: ash

**Comment by nathanchance** [comment] 2023-02-01 20:25
Thanks a lot for the report!

I filed https://github.com/llvm/llvm-project/issues/60460 for the first problem, as that is firmly an upstream LLVM issue. If you could test the diff I have in there, it would be much appreciated!

As for the second problem, I think this is a `podman` issue. I can reproduce it in an Alpine container but not in an Alpine virtual machine and I only need one stage to do it (see my command in the bug report linked above). I see:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /usr/bin/ld.lld -pie -z now -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib/ld-musl-x86_64.so.1 -o bin/llvm-exegesis /usr/lib/Scrt1.o /usr/lib/crti.o /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/12.2.1/crtbeginS.o -L/usr/bin/../lib/gcc/x86_64-alpine-linux-musl/12.2.1 -L/usr/bin/../lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/lib -L/lib -L/usr/lib --as-needed --emit-relocs --color-diagnostics --gc-sections tools/llvm-exegesis/CMakeFiles/llvm-exegesis.dir/llvm-exegesis.cpp.o -rpath $ORIGIN/../lib lib/libLLVMARMAsmParser.a lib/libLLVMAArch64AsmParser.a lib/libLLVMX86AsmParser.a lib/libLLVMARMCodeGen.a lib/libLLVMAArch64CodeGen.a lib/libLLVMX86CodeGen.a lib/libLLVMARMDesc.a lib/libLLVMAArch64Desc.a lib/libLLVMX86Desc.a lib/libLLVMARMDisassembler.a lib/libLLVMAArch64Disassembler.a lib/libLLVMX86Disassembler.a lib/libLLVMARMInfo.a lib/libLLVMAArch64Info.a lib/libLLVMX86Info.a lib/libLLVMMC.a lib/libLLVMMCParser.a lib/libLLVMSupport.a lib/libLLVMTargetParser.a lib/libLLVMExegesis.a lib/libLLVMExegesisX86.a lib/libLLVMExegesisAArch64.a lib/libLLVMipo.a lib/libLLVMFrontendOpenMP.a lib/libLLVMLinker.a lib/libLLVMVectorize.a lib/libLLVMARMDesc.a lib/libLLVMARMInfo.a lib/libLLVMARMUtils.a lib/libLLVMX86AsmParser.a lib/libLLVMX86CodeGen.a lib/libLLVMInstrumentation.a lib/libLLVMX86Desc.a lib/libLLVMX86Disassembler.a lib/libLLVMX86Info.a lib/libLLVMAArch64AsmParser.a lib/libLLVMAArch64CodeGen.a lib/libLLVMAsmPrinter.a lib/libLLVMCFGuard.a lib/libLLVMAArch64Disassembler.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMExegesis.a lib/libLLVMGlobalISel.a lib/libLLVMSelectionDAG.a lib/libLLVMCodeGen.a lib/libLLVMScalarOpts.a lib/libLLVMAggressiveInstCombine.a lib/libLLVMInstCombine.a lib/libLLVMBitWriter.a lib/libLLVMObjCARCOpts.a lib/libLLVMTransformUtils.a lib/libLLVMMCDisassembler.a lib/libLLVMMCA.a lib/libLLVMMCJIT.a lib/libLLVMExecutionEngine.a lib/libLLVMTarget.a lib/libLLVMAnalysis.a lib/libLLVMProfileData.a lib/libLLVMSymbolize.a lib/libLLVMDebugInfoDWARF.a lib/libLLVMDebugInfoPDB.a lib/libLLVMDebugInfoMSF.a lib/libLLVMOrcTargetProcess.a lib/libLLVMOrcShared.a lib/libLLVMObjectYAML.a lib/libLLVMRuntimeDyld.a lib/libLLVMObject.a lib/libLLVMMCParser.a lib/libLLVMMC.a lib/libLLVMDebugInfoCodeView.a lib/libLLVMIRReader.a lib/libLLVMBitReader.a lib/libLLVMAsmParser.a lib/libLLVMTextAPI.a lib/libLLVMAArch64Utils.a lib/libLLVMCore.a lib/libLLVMBinaryFormat.a lib/libLLVMTargetParser.a lib/libLLVMRemarks.a lib/libLLVMBitstreamReader.a lib/libLLVMSupport.a -lrt -ldl -lm lib/libLLVMDemangle.a -lssp_nonshared -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/12.2.1/crtendS.o /usr/lib/crtn.o
clang-15: error: unable to execute command: Aborted (core dumped)
clang-15: error: linker command failed due to signal (use -v to see invocation)
```

Try passing `--pids-limit -1` to your `podman` invocation in `buildme.sh`. Without it, `ld.lld` run into the default PID limit of 2048 then starts throwing errors related to acquiring resolves. This is what I do for all my development containers:

https://github.com/nathanchance/env/blob/9809a5153bbe193e837bb8639daffd969e4c1445/fish/functions/dbxc.fish#L8

Two follow up comments:

- The script already handles adding `bolt` to projects when `--bolt` is specified. If you need `llvm-bolt` and the associated tools in your final toolchain, then you can keep it in your list of projects, but it is unnecessary if you just want the script to automatically perform BOLT on the final `clang`.
- Please consider taking a look at [the work in progress rewrite of tc-build](https://github.com/ClangBuiltLinux/tc-build/pull/226) (commit message in 4a6d1faf8354aeffb2a0b1e9206ec68284d2733e breaks down everything different so far) to see if there are any changes that would adversely affect you. I know there are quite a few users of this project and I am trying to get a good idea of how it is being used so I can avoid breaking people as much as possible with that coming down the pipeline.

**Comment by nathanchance** [comment] 2023-02-01 21:25
The LLVM fix is merged in main now so you should just be able to update the source for that fix.

If my suggestion for `--pids-limit` works, please close this issue, as there should be nothing else to do here. Please open a new issue if you run into any other problems, thanks!

**Comment by Gelbpunkt** [comment] 2023-02-02 19:48
Wow, thanks so much for the incredibly fast response! I'm always surprised when I deal with LLVM developers, fixes tend to be merged before I can test them entirely :smile: 

> The LLVM fix is merged in main now so you should just be able to update the source for that fix.

Thanks a lot for your investigation in that one. It indeed works fine!

> The script already handles adding bolt to projects when --bolt is specified. If you need llvm-bolt and the associated tools in your final toolchain, then you can keep it in your list of projects, but it is unnecessary if you just want the script to automatically perform BOLT on the final clang.

I'm aware of that - but I want use this toolchain to build Python with BOLT instrumentation for Alpine, and their own toolchains don't ship that, so I need to build `llvm-bolt` in stage3.

The `--pids-limit` idea sounds super useful and might have gotten me further, but now I see 
```c
ninja: job failed: : && /build/build/llvm/stage1/bin/clang++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O2 -g -DNDEBUG -Wl,--emit-relocs -fuse-ld=/build/build/llvm/stage1/bin/ld.lld -Wl,--color-diagnostics -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin    -Wl,--gc-sections tools/clang/tools/clang-import-test/CMakeFiles/clang-import-test.dir/clang-import-test.cpp.o -o bin/clang-import-test  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMCore.a  lib/libLLVMSupport.a  lib/libLLVMTargetParser.a  lib/libclangAST.a  lib/libclangBasic.a  lib/libclangCodeGen.a  lib/libclangDriver.a  lib/libclangFrontend.a  lib/libclangLex.a  lib/libclangParse.a  lib/libclangSerialization.a  lib/libclangDriver.a  lib/libLLVMWindowsDriver.a  lib/libLLVMOption.a  lib/libclangSema.a  lib/libclangEdit.a  lib/libclangSupport.a  lib/libclangAnalysis.a  lib/libclangASTMatchers.a  lib/libclangAST.a  lib/libclangLex.a  lib/libclangBasic.a  lib/libLLVMCoverage.a  lib/libLLVMFrontendHLSL.a  lib/libLLVMLTO.a  lib/libLLVMExtensions.a  lib/libPolly.a  lib/libPollyISL.a  lib/libLLVMPasses.a  lib/libLLVMCoroutines.a  lib/libLLVMipo.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMLinker.a  lib/libLLVMIRPrinter.a  lib/libLLVMInstrumentation.a  lib/libLLVMVectorize.a  lib/libLLVMCodeGen.a  lib/libLLVMBitWriter.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTarget.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  lib/libLLVMDemangle.a  -lrt  -ldl  -lm  /lib/libz.so && :
LLVM ERROR: out of memory
Allocation failed
clang-17: error: unable to execute command: Aborted (core dumped)
```
around the same time. I had `top` open the entire time, it never even used a quarter of the system memory, always ~10GB with over 200GB still free. This might be going a bit off-topic for an issue in this repository, but with the flags I pass to podman I *think* there should be no limit to the memory that can be used by the process. I build AOSP within a container with the same flags, and that tends to use more memory. Do you have any ideas on this?

**Comment by nathanchance** [comment] 2023-02-02 20:03
> I'm aware of that - but I want use this toolchain to build Python with BOLT instrumentation for Alpine, and their own toolchains don't ship that, so I need to build `llvm-bolt` in stage3.

No worries, just wanted to make sure it was not a pointless addition :) That is a good optimization idea.

> The `--pids-limit` idea sounds super useful and might have gotten me further, but now I see
> 
> ```c
> ninja: job failed: : && /build/build/llvm/stage1/bin/clang++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O2 -g -DNDEBUG -Wl,--emit-relocs -fuse-ld=/build/build/llvm/stage1/bin/ld.lld -Wl,--color-diagnostics -fprofile-instr-use="/build/build/llvm/profdata.prof" -flto=thin    -Wl,--gc-sections tools/clang/tools/clang-import-test/CMakeFiles/clang-import-test.dir/clang-import-test.cpp.o -o bin/clang-import-test  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMCore.a  lib/libLLVMSupport.a  lib/libLLVMTargetParser.a  lib/libclangAST.a  lib/libclangBasic.a  lib/libclangCodeGen.a  lib/libclangDriver.a  lib/libclangFrontend.a  lib/libclangLex.a  lib/libclangParse.a  lib/libclangSerialization.a  lib/libclangDriver.a  lib/libLLVMWindowsDriver.a  lib/libLLVMOption.a  lib/libclangSema.a  lib/libclangEdit.a  lib/libclangSupport.a  lib/libclangAnalysis.a  lib/libclangASTMatchers.a  lib/libclangAST.a  lib/libclangLex.a  lib/libclangBasic.a  lib/libLLVMCoverage.a  lib/libLLVMFrontendHLSL.a  lib/libLLVMLTO.a  lib/libLLVMExtensions.a  lib/libPolly.a  lib/libPollyISL.a  lib/libLLVMPasses.a  lib/libLLVMCoroutines.a  lib/libLLVMipo.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMLinker.a  lib/libLLVMIRPrinter.a  lib/libLLVMInstrumentation.a  lib/libLLVMVectorize.a  lib/libLLVMCodeGen.a  lib/libLLVMBitWriter.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTarget.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  lib/libLLVMDemangle.a  -lrt  -ldl  -lm  /lib/libz.so && :
> LLVM ERROR: out of memory
> Allocation failed
> clang-17: error: unable to execute command: Aborted (core dumped)
> ```
> 
> around the same time. I had `top` open the entire time, it never even used a quarter of the system memory, always ~10GB with over 200GB still free. This might be going a bit off-topic for an issue in this repository, but with the flags I pass to podman I _think_ there should be no limit to the memory that can be used by the process. I build AOSP within a container with the same flags, and that tends to use more memory. Do you have any ideas on this?

How many cores/threads do you have on this machine? That seems odd to me that LLVM is unable to allocate memory if you are doing ThinLTO and you have 200GB of RAM available... It is possible that parallelism could get the best of you though. I have an 80-core Ampere Altra system with 128GB of RAM that would OOM with ThinLTO because a bunch of linking jobs would be spawned then all together cause the system to go OOM. I dropped the amount of parallelism when linking with a couple of `cmake` defines and I have not seen that problem since:

https://github.com/nathanchance/env/commit/accf2bc366fa36d7e42fc167c84fa1824f466842

**Comment by Gelbpunkt** [comment] 2023-02-02 20:10
> How many cores/threads do you have on this machine?

It's an AMD Epyc 7402P with 24 cores/48 threads and 256GB of memory. The machine is idle, I freshly rebooted it right before and it hovers around 7-10GB memory used for most of the final tasks before randomly displaying that "out of memory" message. I've had issues with full LTO when I was using a Ryzen 9 5950X (16c/32t) with 64GB of memory, but thin always worked. The build completes if I don't enable BOLT in stage3, this is so weird to me.

I'll try using 14 link jobs, but I don't think just enabling BOLT should cause such problems.

**Comment by nathanchance** [comment] 2023-02-02 20:25
Yeah, that is incredibly odd. I would not expect the script to have anything to do with that though, it is not really doing anything special other than passing along values to `cmake` and building things in a specific order. Perhaps it is worth extracting the commands that the script runs via `--show-build-commands`, reproducing it with those commands, and reporting it to LLVM upstream.

It could be resource limit related as well but that seems unlikely if you are able to build AOSP in a similar container.

**Comment by Gelbpunkt** [comment] 2023-02-02 21:45
> I'll try using 14 link jobs, but I don't think just enabling BOLT should cause such problems.

The problem persists if I use 14 link jobs, this is getting ridiculous.

**Closed** 2023-02-02 21:46 UTC
